package com.xiong.domain.dao;

import java.util.List;
import java.util.Map;

import com.xiong.domain.entity.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_table
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	User findByUserNumAndPwd(Map<String, String> map);

	User findByPhoneAndPwd(Map<String, String> map);

	User findByEmailAndPwd(Map<String, String> map);

	int CountofUserNum(String usernum);

	List<User> findAll();
}